CC		= cc
CFLAGS	= -Wall -Wextra -Werror

SRCS	= $(wildcard *.c)

NAME	= ft_display_file

RM		= rm -f

.PHONY:		all clean fclean re
all:		$(NAME)

clean:
			$(RM) $(NAME)

fclean:		clean
			$(RM) $(NAME)

re:			fclean all
